### PR TITLE
Aligned navbar

### PR DESCRIPTION
**Pull request by Tess-Vanta**
### Snapshot

image

### CODE REVIEW

**Comment by riyajha2305** [comment]
> ## In response to issue #62
> ### Snapshot
> image

I'm facing conflicts while merging. Can you please have a quick check once?

**Comment by Tess-Vanta** [comment]
Yes sure let me check once

**Comment by riyajha2305** [comment]
> Yes sure let me check once

See this the conflict which its showing. I am still receiving this.
Screenshot 1943-11-30 at 21 03 49

**Comment by Tess-Vanta** [comment]
> > Yes sure let me check once
> 
> See this the conflict which its showing. I am still receiving this. Screenshot 1943-11-30 at 21 03 49

yes i have seen that and commited after that 
image
How should i merge the recent commits

**Pull request closed without merging**
