### PR TITLE
#28 nav bar problem fixed

### PR DESCRIPTION
**Pull request by ronitblenz**
It was JWoC,
Fixed the Nav bar bug
Now it spaced equally

Plz merge this PR 
Thanks and Regards

### CODE REVIEW

**Comment by riyajha2305** [comment]
> It was JWoC, Fixed the Nav bar bug Now it spaced equally
> 
> Plz merge this PR Thanks and Regards

@ronitblenz ...can you please attach a screenshot in the comment

**Comment by ronitblenz** [comment]
Screenshot 2022-02-05 at 7 10 28 PM

**Comment by riyajha2305** [comment]
> Screenshot 2022-02-05 at 7 10 28 PM

This is the hosted link ss.....things have been changed quite a lot after contributions to this repo. See I have already seen in the codebase for the changes you've made....which are just adding spaces. These cannot be considered as valid changes.

**Comment by ronitblenz** [comment]
> > Screenshot 2022-02-05 at 7 10 28 PM
> 
> This is the hosted link ss.....things have been changed quite a lot after contributions to this repo. See I have already seen in the codebase for the changes you've made....which are just adding spaces. These cannot be considered as valid changes.

So, how to add them in react I tried multiple ways, I thought this worked out

**Comment by riyajha2305** [comment]
> > > Screenshot 2022-02-05 at 7 10 28 PM
> > 
> > 
> > This is the hosted link ss.....things have been changed quite a lot after contributions to this repo. See I have already seen in the codebase for the changes you've made....which are just adding spaces. These cannot be considered as valid changes.
> 
> So, how to add them in react I tried multiple ways, I thought this worked out

You first need to download the repo....and then make changes accordingly....by changing css

**Pull request closed without merging**
