### PR TITLE
Signin css

### PR DESCRIPTION
**Pull request by Shresa**
Modified CSS for the signin / signup page as that of the actual Instagram.

### CODE REVIEW

**Comment by riyajha2305** [comment]
> Modified CSS for the signin / signup page as that of the actual Instagram.

Can u please attach a ss ?

**Comment by Shresa** [comment]
> > Modified CSS for the signin / signup page as that of the actual Instagram.
> 
> Can u please attach a ss ?

yeah sure

**Comment by Shresa** [comment]
Signin page
Screenshot (438)
Signup page
1)
Screenshot (439)

2)
Screenshot (440)

**Comment by riyajha2305** [comment]
> > > Modified CSS for the signin / signup page as that of the actual Instagram.
> > 
> > 
> > Can u please attach a ss ?
> 
> yeah sure

Splendid work @Shresa 🔥🔥🔥....keep going👍

**Pull request merged**
